---
title: "Fish Recruitment Exp Size Distributions"
author: "Kelsey Webber"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format: 
  html:
    css: ../docs/resources/AIMS-style.css
    toc: true
    toc-float: true
    number-sections: true
    number-depth: 5
    embed-resources: true
    code-fold: false
    code-tools: true
    code-summary: "Show the code"
crossref:
  fig-title: '**Figure**'
  fig-labels: arabic
  tbl-title: '**Table**'
  tbl-labels: arabic
engine: knitr
bibliography: ../docs/resources/references.bib
output_dir: ../docs
---

```{r chunks, results='markdown', eval=TRUE, echo = FALSE, cache = TRUE}
knitr::read_chunk('../R/functions.R')
knitr::read_chunk('../R/analysis_recruitment.R')

```

# Preparations

- Load any helper functions (functions.R)

```{r loadFunctions, results='markdown', eval=FALSE}
```

```{r setup, include=FALSE, warnings=FALSE, message=FALSE}
```


- Load required packages (functions.R)

```{r loadPackages, results='markdown', eval = TRUE, warnings = FALSE, message = FALSE}
```

- Prepare paths (functions.R)

```{r preparePaths, results='markdown', eval = TRUE}

```
- Load Fish Recruitment data (analysis_recruitment.R)

```{r recruitment size data, results = 'markdown', eval = TRUE}

```






Some nice plots here: https://www.r-bloggers.com/2021/12/comparing-distributions/
